<?php 
	include 'header.phtml';

	define('MOD_DESC_ADD',		65);
	define('MOD_DESC_EDIT',		66);
	define('MOD_DESC_DEL',		67);

	if($_SESSION['usuario']->usuario_tipo_id == 3) {
		header('Location: '.URL_ROOT.'/tienda');
		exit;
	}

	if(isset($_SESSION['sucursal']) && (!isset($solicitudes) || count($solicitudes)==0)):
?>

	<div class="row page-titles">
		<div class="col-md-5 align-self-center">
			<h3 class="text-themecolor"><i class="fa fa-dollar"></i> Descuentos</h3>
		</div>
	</div>
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-body">
						<?php if(in_array(MOD_DESC_ADD, $permisos)) : ?>
						<button class="btn btn-success pull-right" id="btnAdd"><i class="mdi mdi-plus"></i></button>
						<?php endif; ?>
						<!-- <div class="col-sm-3 pull-right form">
							<div class="input-group">
								<input type="text" id="bus" placeholder="Buscar por nombre" class="form-control">
								<div class="input-group-append">
									<button type="button" class="btn btn-secondary btn-sm" id="btn-bus"><i class="fa fa-search"></i></button>
								</div>
							</div>
						</div> -->

						<h4 class="card-title">Descuentos</h4>
						<h6 class="card-subtitle">Crea, edita y elimina rangos de descuentos</h6>

						<div class="table-responsive">
							<table id="tbl-items" class="table table-hover table-striped">
								<thead>
									<tr>
										<th class="text-center">Descuento</th>
										<th class="text-center">M&iacute;nimo</th>
										<th class="text-center">M&aacute;ximo</th>
										<th class="text-center">Acciones</th>
									</tr>
								</thead>
								<tbody></tbody>
							</table>
						</div>
						
						<div class="row">
							<div class="col-sm-6">
								<div class="dataTables_length" id="editable-datatable_length">
									<label>
										<select name="editable-datatable_length" aria-controls="editable-datatable" class="form-control input-sm" id="cont">
											<option value="10">Ver 10</option>
											<option value="25">Ver 25</option>
											<option value="50">Ver 50</option>
											<option value="100">Ver 100</option>
										</select>
									</label>
									<span id="reg" class="heading-text"></span>
								</div>
							</div>
							<div class="col-sm-6">
								<div class="card-body">
									<nav aria-label="Page navigation example">
										<ul id="pag" class="pagination pull-right"></ul>
									</nav>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--Modales -->
		<div id="frm-item" class="modal" >
			<div class="modal-dialog">
				<div class="modal-content d-flex p-2">
					<div class="modal-header">
						<h3 class="modal-title">Datos del rango</h3>
					</div>
					<div class="modal-body">
						<form class="form p-t-20">
							<div class="form-group">
								<label for="item-descuento">Descuento</label>
								<div class="input-group">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon1">
											<i class="ti-money"></i>
										</span>
									</div>
									<input type="text" class="form-control" id="item-descuento" placeholder="Descuento">
								</div>
							</div>
							<div class="form-group">
								<label for="item-minimo">M&iacute;nimo</label>
								<div class="input-group">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon1">
											<i class="fa fa-chevron-down"></i>
										</span>
									</div>
									<input type="text" class="form-control" id="item-minimo" placeholder="Valor M&iacute;nimo">
								</div>
							</div>
							<div class="form-group">
								<label for="item-maximo">M&aacute;ximo</label>
								<div class="input-group">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon1">
											<i class="fa fa-chevron-up"></i>
										</span>
									</div>
									<input type="text" class="form-control" id="item-maximo" placeholder="Valor M&aacute;ximo">
								</div>
							</div>
							<input type="hidden" id="item-id" value="0">
						</form>
					</div>
					<div class="modal-footer d-flex justify-content-end">
						<button type="submit" class="btn btn-inverse waves-effect waves-light m-r-20" data-dismiss="modal">Cancelar</button>
						<?php if(in_array(MOD_DESC_ADD, $permisos) || in_array(MOD_DESC_EDIT, $permisos)) : ?>
						<button type="submit" class="btn btn-success waves-effect waves-light" id="btnSave">Guardar</button>
					 	<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
		
	</div>
	<?php include 'footer.phtml';?>
	<script src="<?=URL_ROOT?>/assets/plugins/inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/js/mask.init.js"></script>

	<script type="text/javascript">
		$(function() {

			$apiUrl = '<?= URL_API ?>monto_minimo/';

			getItems(0,10);

			$("#item-descuento").inputmask({ alias: "numeric", groupSeparator: ',', digits: 0, digitsOptional: false, mask: 99 });
			$("#item-minimo, #item-maximo").inputmask({ alias: "numeric", groupSeparator: ',', digits: 2, digitsOptional: false });

			function getItems(pag, lim) {
				blockPage();
				$('#tbl-items tbody').empty();
				bus ='';
				bus = $.trim($('#bus').val());
				if(bus == '') bus = 0;;
				$.get($apiUrl+'getAll/'+pag+'/'+lim, function(resp) {
					$.unblockUI();
					if(resp.total > 0) {
						$.each(resp.result, function(index, item) {
							addRow(item);
						});
					}else{
						$('#tbl-items tbody').append('<tr><td colspan="4">No existen descuentos registrados</td></tr>');
					}
					doPagination(resp.total, lim, pag);
				});
			}

			function addRow(item) {
				tr = $('<tr data-id="'+item.id+'"></tr>');
				if($('#tbl-items [data-id="'+item.id+'"]').length > 0) {
					tr = $('#tbl-items [data-id="'+item.id+'"]').parents('tr');
					tr.empty();
				}

				tr.append('<td class="text-center">'+item.descuento+'%</td>');
				tr.append('<td class="text-center">$ '+item.minimo+'</td>');
				tr.append('<td class="text-center">$ '+item.maximo+'</td>');

				tda = $('<td class="text-center"data-id="'+item.id+'"></td>');
				<?php if(in_array(MOD_DESC_EDIT, $permisos)) : ?>
				tda.append('<a href="#" data-popup="tooltip" title="Editar" class="btnEdit"><i class="mdi mdi-pencil"></i></a> ');
				<?php endif; ?>
				<?php if(in_array(MOD_DESC_DEL, $permisos)) : ?>
				tda.append('<a href="#" data-popup="tooltip" title="Eliminar" class="btnDel"><i class="mdi mdi-delete" style="color:red;"></i></a>');
				<?php endif; ?>
				tr.append(tda);

				$('#tbl-items tbody').append(tr);
			}
		
			$('#cont').change(function() { cont = $(this).val(); getItems(0,cont); });

			<?php if(in_array(MOD_DESC_ADD, $permisos)) : ?>
			$('#btnAdd').click(function(e) {
				e.preventDefault();
				clearData();
				$('#frm-item').modal('show');
			});
			<?php endif; ?>

			function clearData() {
				$('.invalid-tooltip').remove();
				$('#frm-item input').val('');
				$('#item-id').val(0);
			}

			$('#frm-item').on('shown.bs.modal', function () { $('#item-descuento').focus(); });
			$('#frm-item').on('hidden.bs.modal', function () { });

			$('tbody').on('click', '.btnEdit', function(event) {
				event.preventDefault();
				$('#frm-item .validation-error-label').remove();
				id = $(this).parents('td').data('id');
				blockPage();
				clearData();
				$.get($apiUrl+'get/'+id, function(data) {
					$.each(data.result, function(index, val) {
						$('#item-'+index).val(val).trigger('change');
					});
					
					$.unblockUI();
					$('#frm-item').modal('show');
				});
			});

			<?php if(in_array(MOD_DESC_DEL, $permisos)) : ?>
			$('tbody').on('click', '.btnDel', function(event) {
				event.preventDefault();
				id = $(this).parents('td').data('id');
				trp = $('#tbl-items [data-id="'+id+'"]').parents('tr');
				nom = trp.find('td:eq(0)').text();
				swal({   
					title: "Eliminar descuento",
					text: "No podrá restaurar la descuento <strong>"+nom+"</strong>",
					type: "warning",   
					html: true,
					showCancelButton: true,   
					cancelButtonText: "Cancelar",
					confirmButtonColor: "#DD6B55",   
					confirmButtonText: "Si, eliminar",
					closeOnConfirm: false 
				}, function() {
					//data: {fk_usuario: 1, fk_session: 1}, 
					blockPage();
					$.ajax({
						url: $apiUrl+'del/'+id,
						type: 'PUT',
						dataType: 'json',
						success: function(resp) {
							if(resp.response) {
								getItems(0, 10);
								swal({
									type: "success",
									title: "¡Listo!",   
									text: "Se eliminó la descuento",   
									timer: 4000
								});
							}
							$.unblockUI();
						}
					});
				});
			});
			<?php endif; ?>

			<?php if(in_array(MOD_DESC_ADD, $permisos) || in_array(MOD_DESC_EDIT, $permisos)) : ?>
			$('#btnSave').click(function() {
				$('.invalid-tooltip').remove();
				id = parseInt($('#item-id').val());
				data = {};

				$.each($('#frm-item').find('input, select'), function(index, elem) {
					ide = $(elem).attr('id').replace('item-','');
					data[ide] = $.trim($(elem).val());
				});

				if(data.minimo=='') { data.minimo = 0; }
				if(data.maximo=='') { data.maximo = 0; }
				$errLabel = $('<div class="invalid-tooltip"></div>');
				if(data.descuento == '') {
					$errLabel.html('Debe ingresar el porcentaje de descuento');
					$('#item-descuento').focus().after($errLabel);
					$errLabel.show();
				} else {
					blockPage();
					if(id == 0) {
						$.post($apiUrl+'add/', data, 
							function(resp) {
								if(resp.response) {
									data.id = resp.result;
									// addRow(data);
									getItems(0, 10);
									$('#item-id').val(0);
									$('#frm-item').modal('hide');									
									swal({
										type: "success",
										title: "¡Listo!",   
										text: "Se guardaron los datos correctamente.",   
										timer: 4000
									});
								}else{
									swal({
										type: "warning",
										title: "Oops!",   
										text: resp.message,   
										timer: 4000
									});
								}
								$.unblockUI();
						},'json');
					} else {
						$.ajax({
							url: $apiUrl+'edit/'+id,
							type: 'PUT',
							dataType: 'json',
							data: data, 
						}).done(function(resp) {
							if(resp.response) {
								// addRow(data);
								getItems(0, 10);
								$('#item-id').val(0);
								$('#frm-item').modal('hide');
								swal({
									type: "success",
									title: "¡Listo!",   
									text: "Se guardaron los datos correctamente.",   
									timer: 4000
								});
							}else{
								swal({
									type: "warning",
									title: "Oops!",   
									text: resp.message,   
									timer: 4000
								});
							}
							$.unblockUI();
						});
					}
				}
			});
			<?php endif; ?>

			$('body').on('click', '#pag li a', function(event) {
				event.preventDefault();
				pag = parseInt($(this).attr('href'));
				cont = parseInt($('#cont').val());
				if(!$(this).parent().hasClass('active') && !$(this).parent().hasClass('active'))
					getItems(pag, cont);
			});
		});
		
	</script>
<?php else: include 'footer.phtml'; endif; ?>