<?php 
	include 'header.phtml';

	if(!defined('MOD_PROVEEDOR_ADD')) {		define('MOD_PROVEEDOR_ADD', 	114); }
	if(!defined('MOD_PROVEEDOR_EDIT')) {	define('MOD_PROVEEDOR_EDIT', 	115); }
	if(!defined('MOD_PROVEEDOR_DEL')) {		define('MOD_PROVEEDOR_DEL', 	116); }

	if($_SESSION['usuario']->usuario_tipo_id == 3) {
		header('Location: '.URL_ROOT.'/tienda');
		exit;
	}

	if(isset($_SESSION['sucursal']) && (!isset($solicitudes) || count($solicitudes)==0)):
?>
	<div class="row page-titles">
		<div class="col-md-5 align-self-center">
			<h3 class="text-themecolor"><i class="mdi mdi-account-circle"></i> Distribuidores</h3>
		</div>
	</div>
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-body">
						<?php if(in_array(MOD_PROVEEDOR_ADD, $permisos)) : ?>
						<button class="btn btn-success pull-right" id="btnAdd"><i class="mdi mdi-plus"></i> Agregar</button>
						<?php endif; ?>

						<h4 class="card-title">Distribuidores</h4>
						<h6 class="card-subtitle">Agrega, edita y da de baja distribuidores de productos</h6>

						<div class="table-responsive">
							<table id="tbl-proveedores" class="table table-hover table-striped table-sm">
								<thead>
									<tr>
										<th class="text-center">Nombre</th>
										<th class="text-center">Tel&eacute;fono</th>
										<th class="text-center">Email</th>
										<th class="text-center">Acciones</th>
									</tr>
								</thead>
								<tbody></tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		<?php if(in_array(MOD_PROVEEDOR_ADD, $permisos) || in_array(MOD_PROVEEDOR_EDIT, $permisos)) : ?>
		<div id="frm-proveedor" class="modal" >
			<div class="modal-dialog">
				<div class="modal-content d-flex p-2">
					<div class="modal-header">
						<h3 class="modal-title">Datos del Distribuidor</h3>
					</div>
					<div class="modal-body">
						<form class="form p-t-20">
							<div class="form-group">
								<label for="proveedor-nombre">Nombre</label>
								<div class="input-group">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon1">
											<i class="ti-user"></i>
										</span>
									</div>
									<input type="text" class="form-control" id="proveedor-nombre" placeholder="Ingresa el Nombre" required>
								</div>
							</div>
							<div class="form-group">
								<label for="proveedor-telefono">Tel&eacute;fono</label>
								<div class="input-group">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon1">
											<i class="fa fa-phone"></i>
										</span>
									</div>
									<input type="text" class="form-control phone-inputmask" id="proveedor-telefono" placeholder="Tel&eacute;fono" required>
								</div>
							</div>
							<div class="form-group">
								<label for="proveedor-correo">Email</label>
								<div class="input-group">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon1">
											<i class="ti-email"></i>
										</span>
									</div>
									<input type="text" class="form-control email-inputmask" id="proveedor-correo" placeholder="Email" required>
								</div>
							</div>
							<input type="hidden" id="proveedor-id" value="0">
						</form>
					</div>
					<div class="modal-footer d-flex justify-content-end">
						<button type="submit" class="btn btn-inverse waves-effect waves-light m-r-20" data-dismiss="modal">Cancelar</button>
						<button type="submit" class="btn btn-success waves-effect waves-light" id="btnSave">Guardar</button>
					</div>
				</div>
			</div>
		</div>
		<?php endif; ?>
	</div>
	<?php include 'footer.phtml';?>
	<script type="text/javascript">
		$(function() {
			$apiUrl = '<?= URL_API ?>proveedor/';
			$('#mnu-dist').addClass('active');

			getProveedores();
			function getProveedores() { blockPage();
				selectedColumns = $('#columns-tbl-proveedores').val(); cleanTable('tbl-proveedores'); $('#tbl-proveedores tbody').empty();
				$.get($apiUrl+'getAll/', function(proveedores) { 
					if(proveedores.total > 0) { $.each(proveedores.result, function(index, item) { addProveedorRow(item); }); }
					createTable('tbl-proveedores', true, selectedColumns); $.unblockUI();
				});
			}

			function addProveedorRow(item) {
				$('#tbl-proveedores [data-id="'+item.id+'"]').remove();
				tr = $('<tr data-id="'+item.id+'"></tr>').appendTo($('#tbl-proveedores tbody'));

				tr.append('<td class="text-left"><small class="nombre">'+item.nombre.toUpperCase()+'</small></td>');
				tr.append('<td class="text-center"><small class="telefono">'+item.telefono+'</small></td>');
				tr.append('<td class="text-center"><small class="email">'+item.correo+'</small></td>');

				tda = $('<td class="text-center"></td>').appendTo(tr);
				acciones = $('<div class="pull-right"></div>').appendTo(tda);
				<?php if(in_array(MOD_PROVEEDOR_EDIT, $permisos)) : ?> acciones.append('<a href="#" data-popup="tooltip" title="Editar" class="btnEditProveedor"><i class="mdi mdi-pencil"></i></a> ');  <?php endif; ?>
				<?php if(in_array(MOD_PROVEEDOR_DEL, $permisos)) : ?> acciones.append('<a href="#" data-popup="tooltip" title="Dar de baja" class="btnDelProveedor"><i class="mdi mdi-delete" style="color:red;"></i></a>'); <?php endif; ?>
			}

			<?php if(in_array(MOD_PROVEEDOR_ADD, $permisos)) : ?>
			$('#btnAdd').click(function(e) { e.preventDefault();
				clearData();
				$('#frm-proveedor').modal('show');
			});
			<?php endif; ?>

			<?php if(in_array(MOD_PROVEEDOR_EDIT, $permisos)) : ?>
			$('tbody').on('click', '.btnEditProveedor', function(event) { event.preventDefault(); blockPage();
				clearData();
				$('#frm-proveedor .validation-error-label').remove();
				id = $(this).parents('tr').data('id');
				
				$.get($apiUrl+'get/'+id, function(proveedor) { proveedor = proveedor.result
					$.each(proveedor, function(index, val) { $('#proveedor-'+index).val(val).trigger('change'); });
					$('#frm-proveedor').modal('show');
					$.unblockUI();
				});
			});
			<?php endif; ?>

			<?php if(in_array(MOD_PROVEEDOR_DEL, $permisos)) : ?>
			$('tbody').on('click', '.btnDelProveedor', function(event) { event.preventDefault(); blockPage();
				id = $(this).parents('tr').data('id');
				trp = $('#tbl-proveedores tr[data-id="'+id+'"]');
				nom = getTrElement('tbl-proveedores', trp).find('.nombre').text();
				swal({ title:"Dar de baja distribuidor", text:"Se dará de baja al distribuidor <strong>"+nom+"</strong>", type:"warning", html:true, showCancelButton:true, cancelButtonText:"Cancelar", confirmButtonColor:"#DD6B55", confirmButtonText:"Si, eliminar", closeOnConfirm:false  }, 
					function(resp) {
						if(resp) {
							$('#tbl-proveedores tbody').empty();
							$.ajax({ url:$apiUrl+'del/'+id, type:'PUT', dataType:'json',
								success: function(resp) {
									if(resp.response) {
										selectedColumns = $('#columns-tbl-proveedores').val(); cleanTable('tbl-proveedores'); trp.remove(); createTable('tbl-proveedores', true, selectedColumns);
										swal({ type:"success", title:"¡Listo!", text:"Se eliminó la distribuidor", timer:4000 });
									} else { swal({ type:"warning", title:"Oops!", text:resp.message, timer:4000 });  }
									$.unblockUI();
								}
							});
						} else { $.unblockUI(); }
					}
				);
			});
			<?php endif; ?>

			<?php if(in_array(MOD_PROVEEDOR_ADD, $permisos) || in_array(MOD_PROVEEDOR_EDIT, $permisos)) : ?>
			$('#frm-proveedor').on('shown.bs.modal', function () { $('#proveedor-nombre').focus(); });

			$('#proveedor-nombre').change(function() {
				$('.invalid-tooltip').remove();
				$.get($apiUrl+'getByNombreMD5/'+$.md5($.trim($(this).val().toLowerCase())), function(proveedor) { if(proveedor.result.length > 0) { proveedor = proveedor.result;
					if(proveedor.length>1 || proveedor[0].id!=parseInt($('#proveedor-id').val())) {
						$errLabel = $('<div class="row invalid-tooltip">Ya existe un proveedor con el mismo nombre</div>');
						$('#proveedor-nombre').after($errLabel);
						$errLabel.show();
						// setTimeout(() => { $('.invalid-tooltip').remove(); }, 4000);
					}
				}}, 'json');
			});

			$('#btnSave').click(function() {
				$('.invalid-tooltip').remove();
				id = parseInt($('#proveedor-id').val());
				data = {};

				$.each($('#frm-proveedor').find('input, select'), function(index, elem) {
					ide = $(elem).attr('id').replace('proveedor-','');
					data[ide] = $.trim($(elem).val());
				});
				data.telefono = data.telefono.replace('(','').replace(')','').replace(' ','').replace('-','').replace(/_/g, '');

				$errLabel = $('<div class="invalid-tooltip"></div>');
				if(data.nombre == '') {
					$errLabel.html('Debe ingresar el nombre');
					$('#proveedor-nombre').focus().after($errLabel);
					$errLabel.show();
				} else if(data.telefono != '' && data.telefono.length != 10) {
					$errLabel.html('El teléfono debe ser a 10 dígitos');
					$('#proveedor-telefono').after($errLabel);
					$errLabel.show();
				} else {
					blockPage();
					if(id == 0) {
						data.status = 1;
						$.post($apiUrl+'add/', data, function(resp) {
							if(resp.response) {
								data.id = resp.result;
								selectedColumns = $('#columns-tbl-proveedores').val(); cleanTable('tbl-proveedores'); addProveedorRow(data); createTable('tbl-proveedores', true, selectedColumns);
								$('#proveedor-id').val(0);
								$('#frm-proveedor').modal('hide');
								swal({ type: "success", title: "¡Listo!", text: "Se guardaron los datos correctamente.", timer: 4000 });
							} else { swal({ type: "warning", title: "Oops!", text: resp.message, timer: 4000 }); }
							$.unblockUI();
						},'json');
					} else {
						$.ajax({ url:$apiUrl+'edit/'+id, type:'PUT', dataType:'json', data:data, }).done(
							function(resp) {
								if(resp.response) {
									tr = $('#tbl-proveedores tr[data-id="'+id+'"]'); trInfo = getTrElement('tbl-proveedores', tr);
									trInfo.find('.nombre').html(data.nombre); trInfo.find('.telefono').html(data.telefono); trInfo.find('.telefono').html(data.telefono); trInfo.find('.email').html(data.correo);
									setTrData('tbl-proveedores', tr, trInfo);
									// getProveedores();
									$('#proveedor-id').val(0);
									$('#frm-proveedor').modal('hide');
									swal({ type: "success", title: "¡Listo!", text: "Se guardaron los datos correctamente.", timer: 4000 });
								} else { swal({ type: "warning", title: "Oops!", text: resp.message, timer: 4000 }); }
								$.unblockUI();
							}
						);
					}
				}
			});

			function clearData() {
				$('.invalid-tooltip').remove();
				$('#frm-proveedor input').val('');
				$('#proveedor-id').val(0);
			}
			<?php endif; ?>

			function getTrElement(tblName, tr) {
				container = $('<div></div>');
				trInfo = $('#'+tblName).DataTable().row(tr).data();
				$.each(trInfo, function(index, trInfoRow) {
					container.append(trInfoRow);
				});
				
				return container;
			}

			function setTrData(tblName, row, trElement) {
				arrContent = [];
				$.each(trElement.children(), function(index, element) { element = $(element);
					tagName = element.prop('tagName').toLowerCase();
					html = '<'+tagName;
					$.each(element[0].attributes, function(index, attr) {
						html += ' '+attr.name+'="'+attr.value+'"';
					});
					html += '>'+element.html()+'</'+tagName+'>';

					arrContent.push(html);
				});

				$('#'+tblName).DataTable().row(row).data(arrContent);
				swal({ type:"success", title:"¡Listo!", text:"Se guardaron los cambios correctamente.", timer:4000 });
			}

			function cleanTable(tbl) {
				if($.fn.dataTable.isDataTable('#'+tbl)) {
					table = $('#'+tbl).DataTable();
					table.destroy();
				}
				$("#nodata").remove();
			}

			function createTable(tbl, paging, arrColumns=null) {
				container = $('<div class="form-inline pull-right" style="overflow: visible"></div>');
				select = $('<select class="selectpicker" multiple data-selected-text-format="static" id="columns-'+tbl+'" title="Mostrar/Ocultar columnas" data-width="fit"></select>').appendTo(container);
				select.append('<option class="form-control-sm" value="0">Nombre</option>');
				select.append('<option class="form-control-sm" value="1">Teléfono</option>');
				select.append('<option class="form-control-sm" value="2">Email</option>');
				select.selectpicker('val', arrColumns!=null? arrColumns: ['0', '1', '2']);
				searchContainer = $('<div class="input-group"></div>').appendTo(container);
				search = $('<input type="text" id="bus" placeholder="Buscar por nombre" class="form-control">').appendTo(searchContainer);
				icon = $('<div class="input-group-append"></div>').appendTo(searchContainer);
				icon.append('<button type="button" class="btn btn-secondary btn-sm" id="btn-bus"><i class="fa fa-search"></i></button>');

				$('#'+tbl).dataTable({
					// scrollY: false,
					scrollX: false,
					paging: paging,
					pagingType: "full_numbers",
					dom: 'Rl<"#toolbar-'+tbl+'">frtip',
					"columnDefs": [
						{"orderable": true, "targets": [0], "visible": ($.inArray("0", select.val())>=0)},
						{"orderable": true, "targets": [1], "visible": ($.inArray("1", select.val())>=0)},
						{"orderable": true, "targets": [2], "visible": ($.inArray("2", select.val())>=0)},
						{"orderable": false, "targets": [3]},
					],
					'order': [0, 'asc']
				});

				$('#toolbar-'+tbl).html(container);
				$('#toolbar-'+tbl+' #bus').keyup(function(e) { $("#"+tbl+"_filter label input").val($.trim($(this).val())).trigger('keyup'); });
				$("#toolbar-"+tbl+" #bus").on("search", function(evt) { $("#"+tbl+"_filter label input").val(undefined).trigger('keyup'); });
				$("#toolbar-"+tbl+" #btn-bus").click(function(evt) { evt.preventDefault(); $("#"+tbl+"_filter label input").val($.trim($('#bus').val())).trigger('keyup'); });
				select.on('changed.bs.select', function(e, index) { blockPage();
					column = $('#'+tbl).DataTable().column(index);
					column.visible(!column.visible());
					$.unblockUI();
				});

				$("#"+tbl+"_filter label").hide();
			}
		});
		
	</script>
<?php else: include 'footer.phtml'; endif; ?>