			<footer class="footer text-right">
				<small>© <?= date('Y') ?> Telecom Grupo Rivera</small>
			</footer>
		</div>
	</div>
	
	<script src="<?=URL_ROOT?>/assets/plugins/bootstrap/js/popper.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/js/jquery.slimscroll.js"></script>
	<script src="<?=URL_ROOT?>/assets/js/waves.js"></script>
	<script src="<?=URL_ROOT?>/assets/js/sidebarmenu.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/moment/moment.js"></script>
	<script src="<?=URL_ROOT?>/assets/js/custom.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/sparkline/jquery.sparkline.min.js"></script>
	<!--script src="<?=URL_ROOT?>/assets/plugins/styleswitcher/jQuery.style.switcher.js"></script-->
	<script src="<?=URL_ROOT?>/assets/plugins/blockUI/jquery.blockUI.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/sweetalert/sweetalert.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/number-format/jquery.number.min.js"></script>
	<!--script src="<?=URL_ROOT?>/assets/plugins/session-timeout/jquery.sessionTimeout.min.js"></script-->
	<script src="<?=URL_ROOT?>/assets/plugins/datatables/jquery.dataTables.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/datatables/dataTables.buttons.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/datatables/buttons.print.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/datatables/jszip.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/datatables/pdfmake.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/datatables/vfs_fonts.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/datatables/buttons.html5.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/bootstrap-select/js/bootstrap-select.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/md5/md5.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/js/mask.init.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/typeahead.js-master/dist/typeahead.bundle.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/lightbox/js/lightbox.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/select2/dist/js/select2.full.min.js" type="text/javascript"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/lightbox/js/lightbox.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/Chart.js/chartjs.min.js"></script>
	<script type="text/javascript">
		/*$.sessionTimeout({
			heading: 'h5',
			title: 'Sesión por expirar',
			message: 'Tu sesión está a punto de expirar. Se cerrará en un minuto. ¿Deseas seguir conectado?',
			warnAfter: 1140000, // Advertencia a los 19 minutuos
			redirUrl: '<?= URL_ROOT ?>/usuario/logout/', // Cerrar sesión si no selecciona nada
			redirAfter: 1200000, // Se cierra a los 20 minutos
			keepAlive: true,
			keepAliveUrl: '<?= URL_ROOT ?>/usuario/renovarToken/', // Renovar token si desea continuar
			logoutUrl: '<?= URL_ROOT ?>/usuario/logout/', // Cerrar sesión
			keepAliveButton: 'Seguir conectado',
			logoutButton: 'Salir',
			ignoreUserActivity: true,
		});*/
	</script>
</body>
</html>