<?php 
	include 'header.phtml';

	define('MOD_GARANTIAS', 	18);
	define('MOD_INGRESO_ADD', 	120);
	define('MOD_INGRESO_DEL', 	121);
	define('MOD_COSTO_ADD', 	122);
	define('MOD_STATUS_UPD', 	123);

	if(isset($_SESSION['sucursal']) && (!isset($solicitudes) || count($solicitudes)==0)):
?>
	<link href="<?= URL_ROOT ?>/assets/plugins/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet" />

	<div class="row page-titles">
		<div class="col-md-5 align-self-center">
			<h3 class="text-themecolor"><i class="mdi mdi-backup-restore fa-lg"></i> Garantías</h3>
		</div>
		<div class="col-sm-7">
			<div class="form-inline pull-right <?= $_SESSION['sucursal'] > 0 ? 'hide' : '' ?>">
				<input type="date" class="form-control form-control-sm m-r-10" id="rpt-ini" value="<?= date('Y-m-01') ?>">
				<input type="date" class="form-control form-control-sm m-r-10" id="rpt-fin" value="<?= date('Y-m-d') ?>">
				<select id="rpt-suc" class="form-control form-control-sm">
					<option value="0">Todas las sucursales</option>
				</select>
			</div>
		</div>
	</div>

	<div class="container-fluid">
		<div class="card">
			<div class="card-header">
				<div class="pull-right form-inline">
					<div class="input-group input-group-sm">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fa fa-filter"></i></span>
						</div>
						<input type="search" placeholder="Buscar por cliente o equipo" class="form-control form-control-sm filter">
					</div>
					<?php if(in_array(MOD_INGRESO_ADD, $permisos)) : ?>
					<button class="btn btn-sm btn-success m-l-10 <?= intval($_SESSION['sucursal']) == 0 ? 'hide' : '' ?>" id="btnAdd"><i class="mdi mdi-plus"></i></button>
					<?php endif; ?>
				</div>
				<h4 class="card-title">Equipos en garantía</h4>
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table id="tbl-items" class="table table-sm table-striped table-hover">
						<thead>
							<tr>
								<th>Fecha</th>
								<th class="<?= $_SESSION['sucursal'] > 0 ? 'hide' : '' ?>">Sucursal</th>
								<th>Cliente</th>
								<th>Equipo</th>
								<th>Fecha Venta</th>
								<th class="text-right">Importe</th>
								<th class="<?= $_SESSION['sucursal'] > 0 ? 'hide' : '' ?>">Distribuidor</th>
								<th class="text-center">Entrega</th>
								<th>Comentarios</th>
								<th class="text-center">Estado</th>
								<th></th>
							</tr>
						</thead>
						<tbody></tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	
	<?php if(in_array(MOD_INGRESO_ADD, $permisos)) : ?>
	<div id="frm-item" class="modal" data-backdrop="static" data-keyboard="false" tabindex="-1">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h3 class="modal-title"><i class="mdi mdi-backup-restore"></i> Ingresar Equipo</h3>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form-horizontal">
						<div class="form-group row m-b-10">
							<label for="item-imei" class="col-md-4 col-form-label">No. IMEI:</label>
							<div class="col-md-8">
								<input type="number" class="form-control text-center" id="item-imei" placeholder="# IMEI" required maxlength="15">
							</div>
						</div>
						<div class="form-group row m-b-10">
							<label for="item-producto" class="col-md-4 col-form-label">Equipo:</label>
							<div class="col-md-8">
								<input type="text" class="form-control" id="item-producto" placeholder="Descripción equipo" readonly>
							</div>
						</div>
						<div class="form-group row m-b-10">
							<label for="item-fecha" class="col-md-4 col-form-label">Venta:</label>
							<div class="col-md-8">
                                <div class="input-group">
                                    <div class="input-group-prepend">
										<span class="input-group-text"><i class="mdi mdi-calendar"></i></span>
									</div>
								    <input type="text" class="form-control" id="item-fecha" placeholder="Fecha venta" readonly>
                                </div>
							</div>
						</div>
						<div class="form-group row m-b-10">
							<label for="item-importe" class="col-md-4 col-form-label">Importe</label>
							<div class="col-md-8">
								<div class="input-group">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon1">$</span>
									</div>
									<input type="text" class="form-control text-right" id="item-importe" placeholder="Importe" readonly>
								</div>
							</div>
						</div>
						<div class="form-group row m-b-10">
							<label for="item-cliente" class="col-md-4 col-form-label">Cliente</label>
							<div class="col-md-8">
								<input type="text" class="form-control" id="item-cliente" placeholder="Nombre completo del cliente" required>
							</div>
						</div>
						<div class="form-group row m-b-0">
							<label class="col-md-4 col-form-label" for="item-motivo">Motivo</label>
							<div class="col-md-8">
								<textarea class="form-control" id="item-motivo" placeholder="Motivo" rows="3"></textarea>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
                    <input type="hidden" id="item-venta_id" value="0">
                    <input type="hidden" id="item-producto_id" value="0">
					<button type="submit" class="btn btn-inverse waves-effect waves-light m-r-20" data-dismiss="modal">Cancelar</button>
					<?php if(in_array(MOD_INGRESO_ADD, $permisos)) : ?>
					<button type="submit" class="btn btn-success waves-effect waves-light" id="btnSave">Guardar</button>
					<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
	<?php endif; ?>
		
	<?php include 'footer.phtml';?>
	<script src="<?=URL_ROOT?>/assets/plugins/inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/js/mask.init.js"></script>
	<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.js"></script>

	<script type="text/javascript">
		$(function() {
			$apiUrl = '<?= URL_API ?>';
			
			arrSuc = [];
			function getItems(){
				blockPage();
				$.get($apiUrl+"pos/getGarantias/<?= $_SESSION['sucursal'] ?>",
					function (data) {
						$('#rpt-suc').empty().append('<option value="0">Todas las sucursales</option>');
						arrSuc = [];
						if(data.length > 0){
							$.each(data, function (index, item) { 
								addRow(item);
								if(!arrSuc.includes(item.sucursal_id)){ $('#rpt-suc').append('<option value="'+item.sucursal+'">'+item.sucursal+'</option>'); arrSuc.push(item.sucursal_id)};
							});
						}else{
							$('#tbl-items tbody').append('<tr class="no-data"><td colspan="11"><small>No hay reparaciones pendientes</small></td></tr>');
						}
						$('[data-toggle="popover"]').popover();
						$.unblockUI();
					},
					"json"
				);
			}
			getItems();

			$.fn.editable.defaults.mode = 'inline';
			$.fn.editable.defaults.url = '<?= URL_API ?>pos/garantia/set';
			$.fn.editable.defaults.source = ['En Almacen', 'En Reparación', 'Reparado', 'No Reparado'];
			function addRow(item){
				tr = $('<tr></tr>');

				tr.append('<td>'+item.fecha+'</td>');
				tr.append('<td class="<?= $_SESSION['sucursal'] > 0 ? 'hide' : '' ?>">'+item.sucursal+'</td>');
				tr.append('<td>'+item.cliente+'</td>');
				obs = '<i class="mdi mdi-comment pull-right" data-container="body" title="Motivo" data-toggle="popover" data-content="'+item.motivo+'" data-trigger="hover"></i>';
				tr.append('<td><small>'+item.marca+' '+item.producto+' <strong>'+item.imei+'</strong></small>'+obs+'</td>');
				tr.append('<td><small>'+item.fecha_venta+'</small></td>');
                tr.append('<td class="text-right"><small>'+item.importe+'</small></td>');

                tr.append('<td class="<?= $_SESSION['sucursal'] > 0 ? 'hide' : '' ?>">'+item.distribuidor+'</td>');
                
				<?php if(in_array(MOD_COSTO_ADD, $permisos)) : ?>
				entrega = '<a href="#" class="editable" data-type="date" data-pk="'+item.id+'" data-name="entrega">'+(item.entrega!=null?item.entrega:'--')+'</a>';
				tr.append('<td class="text-center"><span>'+entrega+'</span></td>');
				if(item.estado.indexOf('Entregado') > -1) comm = '<span>'+(item.comentarios!=''?item.comentarios:'--')+'</span>';
				else comm = '<a href="#" class="editable" data-pk="'+item.id+'" data-name="comentarios">'+item.comentarios+'</a>';
				tr.append('<td><span>'+comm+'</span></td>');
				<?php else : ?>
				tr.append('<td class="text-center"><small>'+(item.entrega!=null?item.entrega:'--')+'</small></td>');
				tr.append('<td><small>'+item.comentarios+'</small></td>');
				<?php endif; ?>
				
                edo = 'secondary'; if(item.estado == 'En Reparación') edo = 'primary'; if(item.estado.indexOf('Reparado') > -1) edo = 'warning';
				if(item.estado.indexOf('Entregado') > -1) edo = 'success';
				<?php if(in_array(MOD_STATUS_UPD, $permisos)) : ?>
				if(item.estado.indexOf('Entregado') > -1) estado = '<span class="badge badge-'+edo+'">'+item.estado+'</span>';
				else estado = '<a href="#" class="editable badge badge-'+edo+'" data-type="select" data-pk="'+item.id+'" data-name="estado" data-value="'+item.estado+'">'+item.estado+'</a>';
				tr.append('<td class="text-center">'+estado+'</td>');
				<?php else : ?>
				tr.append('<td class="text-center"><span class="badge badge-'+edo+'">'+item.estado+'</span></td>');
				<?php endif; ?>

				tda = $('<td class="text-right" data-id="'+item.id+'"></td>');
				<?php if(in_array(MOD_INGRESO_DEL, $permisos)) : ?>
				if(item.estado == 'En Sucursal') tda.append('<a href="#" data-popup="tooltip" title="Eliminar" class="btnDel"><i class="mdi mdi-delete" style="color:red;"></i></a>');
				<?php endif; ?>
				tr.append(tda);
				
				$('#tbl-items .no-data').remove();
				$('#tbl-items tbody').append(tr);
				$('.editable').editable();
				$('[data-toggle="popover"]').popover();
			}
		
			$('.filter').keyup(function(e) { 
				q = $.trim($(this).val()).toUpperCase();
				$.each($(this).parents('.card').find('table tbody tr'), function (index, elem) { 
					cli = $(elem).find('td:eq(2)').text().toUpperCase();
					equi = $(elem).find('td:eq(3)').text().toUpperCase();
					suc = $(elem).find('td:eq(1)').text();
					if((cli.indexOf(q) > -1 || equi.indexOf(q) > -1) && ($('#rpt-suc').val() == '0' || suc == $('#rpt-suc').val())){
						$(elem).css('display', '');
					}else{
						$(elem).css('display', 'none');
					}
				});
			 });

			 $(".filter").on("search", function(evt){
				$.each($(this).parents('.card').find('table tbody tr'), function (index, elem) { 
					$(elem).css('display', '');
				});
			});

			$('#rpt-suc').change(function(){
				$('.filter').val('');
				suc = $(this).val();
				if(suc == '0'){
					$.each($('#tbl-items tbody tr'), function (index, elem) { 
						$(elem).css('display', '');
					});
				}else{
					$.each($('#tbl-items tbody tr'), function (index, elem) { 
						if($(elem).find('td:eq(1)').text() == suc){
							$(elem).css('display', '');
						}else{
							$(elem).css('display', 'none');
						}
					});
				}
			});

			$('#rpt-ini, #rpt-fin').change(function(){
				blockPage();
				$('#tbl-items tbody').empty();
				$.get($apiUrl+"pos/getGarantias/"+$('#rpt-ini').val()+"/"+$('#rpt-fin').val(),
					function (data) {
						$('#rpt-suc').empty().append('<option value="0">Todas las sucursales</option>');
						arrSuc = [];
						if(data.length > 0){
							$.each(data, function (index, item) { 
								addRow(item);
								if(!arrSuc.includes(item.sucursal_id)){ $('#rpt-suc').append('<option value="'+item.sucursal+'">'+item.sucursal+'</option>'); arrSuc.push(item.sucursal_id)};
							});
						}else{
							$('#tbl-items tbody').append('<tr class="no-data"><td colspan="11"><small>No hay reparaciones pendientes en el periodo seleccionado</small></td></tr>');
						}
						$('[data-toggle="popover"]').popover();
						$.unblockUI();
					},
					"json"
				);
			});

			<?php if(in_array(MOD_INGRESO_ADD, $permisos)) : ?>
			$('#btnAdd').click(function(e) {
				e.preventDefault();
				$('#frm-item input, #item-motivo').val('');
				$('#frm-item').modal('show');
			});

            $('#item-imei').change(function(){
                imei = $.trim($(this).val());
                if(imei != ''){
                    blockPage();
                    $.get($apiUrl+"venta_detalle/findBySku/"+imei,
                        function (data, textStatus, jqXHR) {
                            if(data.response){
                                $.each(data.result, function (index, value) { 
                                    $('#item-'+index).val(value); 
                                });
                                $('#item-cliente').focus();
                            }else{
                                $('#item-imei').focus();
                                swal({
									type: "warning",
									title: "Oops!",   
									text: 'No se encotró el IMEI. Verifique e intente nuevamente.',   
									timer: 4000
								});
                            }
                            $.unblockUI();
                        },
                        "json"
                    );
                }
            });
			<?php endif; ?>

			$('#frm-item').on('shown.bs.modal', function () { $('#item-imei').focus(); });

			<?php if(in_array(MOD_INGRESO_DEL, $permisos)) : ?>
			$('tbody').on('click', '.btnDel', function(event) {
				event.preventDefault();
				id = $(this).parent().data('id');
				trp = $(this).parents('tr');
				swal({   
					title: "Eliminar registro",
					text: "No podrá revertir esta acción",
					type: "warning",   
					html: true,
					showCancelButton: true,   
					cancelButtonText: "Cancelar",
					confirmButtonColor: "#DD6B55",   
					confirmButtonText: "Si, eliminar",
					closeOnConfirm: false 
				}, function() {
					//data: {fk_usuario: 1, fk_session: 1}, 
					blockPage();
					$.ajax({
						url: $apiUrl+'pos/delGarantia/'+id,
						type: 'PUT',
						dataType: 'json',
						success: function(resp) {
							if(resp.response) {
								trp.remove();
								swal({
									type: "success",
									title: "¡Listo!",   
									text: "Se eliminó el registro",   
									timer: 4000
								});
							}
							$.unblockUI();
						}
					});
				});
			});
			<?php endif; ?>

			<?php if(in_array(MOD_INGRESO_ADD, $permisos)) : ?>
			$('#btnSave').click(function() {
				$('.invalid-tooltip').remove();
				data = {};
				$.each($('#frm-item input'), function (index, elem) { 
					ide = $(elem).attr('id').replace('item-','');
					data[ide] = $.trim($(elem).val());
				});
				data.motivo = $.trim($('#item-motivo').val());

				$errLabel = $('<div class="invalid-tooltip"></div>');
				if(data.cliente == '') {
					$errLabel.html('Debe ingresar el cliente');
					$('#item-cliente').after($errLabel);
					$errLabel.show();
				}else if(data.imei == '') {
					$errLabel.html('Debe ingresar el IMEI');
					$('#item-imei').after($errLabel);
					$errLabel.show();
				}else if(data.venta_id == '' || data.producto_id == '') {
					$errLabel.html('Debe ingresar el IMEI');
					$('#item-marca').after($errLabel);
					$errLabel.show();
				}else if(data.motivo == '') {
					$errLabel.html('Debe ingresar el motivo');
					$('#item-motivo').after($errLabel);
					$errLabel.show();
				}else{
					blockPage();
					if(data.anticipo == '') data.anticipo = 0;
					$.post($apiUrl+'pos/addGarantia/', data, 
						function(resp) {
							if(resp.response) {
								data.id = resp.result;
								data.fecha = resp.fecha;
								data.estado = 'En Sucursal';
								addRow(data);
								$('#frm-item').modal('hide');									
								swal({
									type: "success",
									title: "¡Listo!",   
									text: "Se guardaron los datos correctamente.",   
									timer: 4000
								});
							}else{
								swal({
									type: "warning",
									title: "Oops!",   
									text: resp.message,   
									timer: 4000
								});
							}
							$.unblockUI();
					},'json');
				}
			});
			<?php endif; ?>
		});
		
	</script>
<?php else: include 'footer.phtml'; endif; ?>