<?php include 'header.phtml'?>           
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">Dashboard</h3>
                </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard</li>
                    </ol>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            

                <!-- ============================================================== -->
                <!-- End PAge Content -->
                <!-- ============================================================== -->
            
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            <footer class="footer">
                © 2019 DDS.Media <?php print_r($name);?>
            </footer>
            <!-- ============================================================== -->
            <!-- End footer -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="<?=URL_ROOT?>/assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="<?=URL_ROOT?>/assets/plugins/bootstrap/js/popper.min.js"></script>
    <script src="<?=URL_ROOT?>/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="<?=URL_ROOT?>/assets/js/jquery.slimscroll.js"></script>
    <!--Wave Effects -->
    <script src="<?=URL_ROOT?>/assets/js/waves.js"></script>
    <!--Menu sidebar -->
    <script src="<?=URL_ROOT?>/assets/js/sidebarmenu.js"></script>
    <!--stickey kit -->
    <script src="<?=URL_ROOT?>/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
    <!--Custom JavaScript -->
    <script src="<?=URL_ROOT?>/assets/js/custom.min.js"></script>
    <!-- ============================================================== -->
    <!-- This page plugins -->
    <!-- ============================================================== -->
    <!--sparkline JavaScript -->
    <script src="<?=URL_ROOT?>/assets/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!--morris JavaScript >
    <script src="<?=URL_ROOT?>/assets/plugins/raphael/raphael-min.js"></script>
    <script src="<?=URL_ROOT?>/assets/plugins/morrisjs/morris.min.js"></script-->
    <!-- Chart JS >
    <script src="<?=URL_ROOT?>/assets/js/dashboard1.js"></script-->
    <!-- ============================================================== -->
    <!-- Style switcher -->
    <!-- ============================================================== -->
    <script src="<?=URL_ROOT?>/assets/plugins/styleswitcher/jQuery.style.switcher.js"></script>
</body>

</html>