<?php
    include 'core/defines.php';
    ini_set('error_reporting',0);

    if(isset($_SESSION['usuario'])) {
        $user = $_SESSION['usuario'];
    }else{
        header('Location: '.URL_ROOT.'/login');
        exit();
    }

    define('DATOS_RAZON', 'Viama Comercializadora S.A. de C.V.');
    define('DATOS_RFC', 'VCO190826SD6');
    define('DATOS_REGIMEN', '601 Régimen de las Personas Morales');
    define('DATOS_DIRECCION', 'Palo de Agua No 155, Campestre Villas del Alamo, Mineral de la Reforma, Hidalgo, CP 42184');
    define('DATOS_CP', '42184');

	$remUrl = 'data/cotizaciones/COT_'.$cotizacion->folio.'.pdf';
	// HEADER
	$info->logo = true; 
	$info->logoUrl = 'assets/images/logo.png';

	// $arrMetodo = array('PUE' => 'Pago en una sola exhibición', 'PPD' => 'Pago en parcialidades o diferido');
	// $arrForma = array('01' => 'Efectivo', '02' => 'Cheque', '03' => 'Transferencia electrónica', '04' => 'Tarjeta de crédito', '08' => 'Vales de despensa', '28' => 'Tarjeta de débito', '99' => 'Por definir');
	$arrUso = array('G01' => 'Adquisición de mercancias', 'G03' => 'Gastos en general', 'I02' => 'Mobilario y equipo de oficina por inversiones', 'P01' => 'Por definir');

	$info->fecha = $cotizacion->fecha;
	$info->no_doc = $cotizacion->folio;
	// $info->metodo = $arrMetodo[$venta->metodo_pago];
	// $info->forma = $arrForma[$venta->forma_pago];
	$info->lugar = DATOS_CP;
	$info->emisor = DATOS_RAZON." ".DATOS_RFC."\n";
	$info->emisor .= DATOS_DIRECCION."\n";
	$info->emisor .= DATOS_REGIMEN;

	$info->receptor = $cliente->razon_social." ".$cliente->rfc."\n";
	$info->receptor .= "Uso de CFDi: ".$arrUso[$cliente->uso_cfdi]."\n";
	$info->receptor .= $cliente->direccion."\n";

	$arrColor = array(
			'',array(0,0,0),
			array(67,45,127),array(0,139,139),
			array(128,0,0),array(255,255,255));
	$info->color = 1;
	$info->bgColor = $arrColor[$info->color];


	require_once('core/tcpdf/config/lang/spa.php');
	require_once('core/tcpdf/tcpdf.php');
	 
	class MYPDF extends TCPDF {
		protected $info;

		public function Header() {
			if($this->info->logo) {
				$this->setJPEGQuality(90);
				list($width, $height) = getimagesize($this->info->logoUrl);
				$nh = $height * 130 / $width;
				if($nh < 41) {
					$ltMrg = ((40 - $nh) / 2) + 10;
					$this->Image($this->info->logoUrl, 10, $ltMrg, 130, 0);
				}else{
					$nw = $width * 41 / $height;
					$ltMrg = ((130 - $nw) / 2) + 10;
					$this->Image($this->info->logoUrl, $ltMrg, 10, 0, 40);
				}
			}

			$this->SetY(10);
			$this->SetFillColorArray($this->info->bgColor);
			$this->Cell(136, 5, '');
			$this->printHeader(60, 5, 'COTIZACIÓN', 1, 'C', 10);
			$this->SetTextColor(255, 0, 0);
			$this->SetFont(PDF_FONT_NAME_MAIN, 'B', 9);
			$this->Cell(136, 5, '');
			$this->Cell(60, 5, $this->info->no_doc, 1, 1, 'C');
			$this->Cell(136, 5, '');
			$this->printHeader(60, 5, 'Fecha y Hora de emisión', 1, 'C', 9);
			$this->Cell(136, 5, '');
			$this->Cell(60, 5, $this->info->fecha, 1, 1, 'C');
			// $this->Cell(136, 5, '');
			// $this->printHeader(60, 5, 'Método de Pago', 1, 'C', 9);
			// $this->Cell(136, 5, '');
			// $this->MultiCell(60, 5, $this->info->metodo, 1, 'C', 0, 1);
			// $this->Cell(136, 5, '');
			// $this->printHeader(60, 5, 'Forma de Pago', 1, 'C', 9);
			// $this->Cell(136, 5, '');
			// $this->MultiCell(60, 5, $this->info->forma, 1, 'C', 0, 1);
			$this->SetY(50);
			$this->Cell(0, 5, 'Lugar de Expedición: '.$this->info->lugar, 0, 1);
		}

		public function Footer() {
			if($this->info->color < 5)
				$this->SetTextColorArray($this->info->bgColor);
			else
				$this->SetTextColor(0, 0, 0);
			$paginas = "Página " . $this->PageNo() . ' de ' . $this->getAliasNbPages();
			$this->SetY(-15);
			// $publiY = $this->GetY() - 15;
		    $this->SetFont(PDF_FONT_NAME_MAIN, '', 7);
			$this->Cell(0, 3, 'Este documento tiene validez durante 30 días', 0, 1, 'C');
			$this->SetY(-11);
		    $this->Cell(0, 3, 'Este documento es informativo únicamente y no tiene validez oficial', 0, 1, 'C');
		    $this->Cell(0, 3, $paginas, 0, 0, 'C');
		}

		public function setInfo($info) {
			$this->info = $info;
		}

		public function printHeader($w, $h, $txt, $ln, $align, $font) {
			if($this->info->color < 5)
				$this->SetTextColor(255, 255, 255);
			else
				$this->SetTextColor(0, 0, 0);
			$this->SetFont(PDF_FONT_NAME_MAIN, 'B', $font);
			$this->Cell($w, $h, $txt, 1, $ln, $align, 1);
			if($this->info->color < 5)
				$this->SetTextColorArray($this->info->bgColor);
			else
				$this->SetTextColor(0, 0, 0);
			$this->SetFont(PDF_FONT_NAME_MAIN, '', ($font-1));
		}
	}


$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
$pdf->setInfo($info);
$pdf->SetFillColorArray($info->bgColor);
 
$pdf->SetCreator('www.ddsmedia.net');
$pdf->SetAuthor('Conforta');
$pdf->SetTitle('Cotización');
//$pdf->SetSubject('Estado de cuenta del '.$info->fecha);
$pdf->SetKeywords('');
 
// add a page
//$pdf->AliasNbPages(); 
$pdf->AddPage();
$pdf->SetY(60);

// $pdf->printHeader(93, 5, 'EMISOR', 0, 'C', 9);
// $pdf->Cell(10);
$pdf->SetX(113);
$pdf->printHeader(93, 5, 'CLIENTE', 1, 'C', 9);
// $pdf->MultiCell(93, 5, $info->emisor, 1, 'L', 0, 1);
// $currY = $pdf->GetY();
$pdf->SetXY(113,65);
$pdf->MultiCell(93, 5, $info->receptor, 1, 'L', 0, 1);
if($pdf->GetY() > $currY)
	$currY = $pdf->GetY();
$pdf->SetY($currY+2);

// $pdf->Ln(5);
// HEADER DE CONCEPTOS
	$pdf->printHeader(15, 5, 'Cant', 0, 'C', 9);
	$pdf->printHeader(20, 5, 'Unidad', 0, 'C', 9);
	$pdf->printHeader(15, 5, 'Cve SAT', 0, 'C', 9);
	$pdf->printHeader(96, 5, 'Concepto', 0, 'C', 9);
	$pdf->printHeader(25, 5, 'P Unitario', 0, 'C', 9);
	$pdf->printHeader(25, 5, 'Importe', 1, 'C', 9);

foreach ($detalles as $det) {
    $pdf->SetFont(PDF_FONT_NAME_MAIN, '', 9);

    $pdf->setX(60);		$y0 = $pdf->GetY();
    $desc = $det->nombre.' '.$det->modelo.' '.$det->tamano;
    $pdf->MultiCell(96, 5, $desc, 0, 'L', 0, 1);
    $height = $pdf->GetY() - $y0;

    $pdf->setXY(10, $y0);
    $pdf->SetFont(PDF_FONT_NAME_MAIN, '', 8);
    $pdf->Cell(15, $height, $det->cantidad, 1, 0, 'C', 0);
	$pdf->Cell(20, $height, substr($det->unidad_sat.' PIEZA',0,14), 1, 0, 'C', 0);
	$pdf->Cell(15, $height, $det->clave_sat, 1, 0, 'C', 0);
    $pdf->SetFont(PDF_FONT_NAME_MAIN, '', 9);
	$pdf->Cell(96, $height, '', 1, 0, 'L', 0);
	$pdf->Cell(25, $height, number_format($det->costo,2), 1, 0, 'R', 0);
	$pdf->Cell(25, $height, number_format($det->importe,2), 1, 1, 'R', 0);
	$currY = $pdf->GetY();

	if($pdf->GetY() > 246) addPagina();
}

function addPagina() {
	global $pdf;
	$pdf->AddPage();
	$pdf->SetY(60);
	printHeaderCon();
}

$pdf->Ln(3);		$currY = $pdf->GetY();
// $pdf->MultiCell(120, 5, $venta->condiciones_pago, 0, 'L', 0, 1);
$nextY = $pdf->GetY();

$pdf->setXY(130,$currY);
$pdf->printHeader(36, 5, 'SUBTOTAL', 0, 'R', 9);
$pdf->SetFont(PDF_FONT_NAME_MAIN, '', 9);
$pdf->Cell(40, 5, "$ ".number_format($cotizacion->subtotal,2)." MXN", 1, 1, 'R', 0, '', 0);

if($cotizacion->descuento > 0) {
	$pdf->setX(130);
	$pdf->printHeader(36, 5, 'Descuento', 0, 'R', 9);
	$pdf->SetFont(PDF_FONT_NAME_MAIN, '', 9);
	$pdf->Cell(40, 5, "$ ".number_format($cotizacion->descuento,2)." MXN", 1, 1, 'R', 0, '', 0);
}

// IVA
	$pdf->setX(130);
	$pdf->printHeader(36, 5, 'IVA: ', 0, 'R', 9);
	$pdf->SetFont(PDF_FONT_NAME_MAIN, '', 9);
	$pdf->Cell(40, 5, "$ ".number_format((($cotizacion->total / 1.16) * 0.16),2)." MXN", 1, 1, 'R', 0, '', 0);

$pdf->setX(130);
$pdf->printHeader(36, 5, 'TOTAL: ', 0, 'R', 10);
$pdf->SetFont(PDF_FONT_NAME_MAIN, 'B', 10);
$pdf->Cell(40, 5, "$ ".number_format($cotizacion->total,2)." MXN", 1, 1, 'R', 0, '', 0);
$pdf->SetFont(PDF_FONT_NAME_MAIN, '', 9);

if($pdf->GetY() > $nextY)
	$nextY = $pdf->GetY();

$pdf->SetY($nextY+5);
$pdf->MultiCell(0, 5, 'TOTAL CON LETRA: '.num2letras(str_replace(',', '', number_format($cotizacion->total,2)), 'MXN'), 0, 'L', 0, 1);
$pdf->SetFont(PDF_FONT_NAME_MAIN, '', 8);
// //$pdf->Cell(0, 5, 'Forma de Pago: '.$venta->forma_pago, 0, 1, 'L', 0);
// $pdf->MultiCell(0, 5, 'Condiciones de Pago: '.$venta->condiciones_pago, 0, 'L', 0, 1);

$dest = 'FD';
// if(isset($_GET['dl']))	$dest = 'FD';
$pdf->Output($remUrl, $dest);
if($dest == 'F') echo URL_ROOT.'/'.$remUrl;

	function num2letras($num, $mon, $fem = true, $dec = true) { 
		//if (strlen($num) > 14) die("El n?mero introducido es demasiado grande"); 
	   $matuni[2]  = "dos"; 
	   $matuni[3]  = "tres"; 
	   $matuni[4]  = "cuatro"; 
	   $matuni[5]  = "cinco"; 
	   $matuni[6]  = "seis"; 
	   $matuni[7]  = "siete"; 
	   $matuni[8]  = "ocho"; 
	   $matuni[9]  = "nueve"; 
	   $matuni[10] = "diez"; 
	   $matuni[11] = "once"; 
	   $matuni[12] = "doce"; 
	   $matuni[13] = "trece"; 
	   $matuni[14] = "catorce"; 
	   $matuni[15] = "quince"; 
	   $matuni[16] = "dieciseis"; 
	   $matuni[17] = "diecisiete"; 
	   $matuni[18] = "dieciocho"; 
	   $matuni[19] = "diecinueve"; 
	   $matuni[20] = "veinte"; 
	   $matunisub[2] = "dos"; 
	   $matunisub[3] = "tres"; 
	   $matunisub[4] = "cuatro"; 
	   $matunisub[5] = "quin"; 
	   $matunisub[6] = "seis"; 
	   $matunisub[7] = "sete"; 
	   $matunisub[8] = "ocho"; 
	   $matunisub[9] = "nove"; 

	   $matdec[2] = "veint"; 
	   $matdec[3] = "treinta"; 
	   $matdec[4] = "cuarenta"; 
	   $matdec[5] = "cincuenta"; 
	   $matdec[6] = "sesenta"; 
	   $matdec[7] = "setenta"; 
	   $matdec[8] = "ochenta"; 
	   $matdec[9] = "noventa"; 
	   $matsub[3]  = 'mill'; 
	   $matsub[5]  = 'bill'; 
	   $matsub[7]  = 'mill'; 
	   $matsub[9]  = 'trill'; 
	   $matsub[11] = 'mill'; 
	   $matsub[13] = 'bill'; 
	   $matsub[15] = 'mill'; 
	   $matmil[4]  = 'millones'; 
	   $matmil[6]  = 'billones'; 
	   $matmil[7]  = 'de billones'; 
	   $matmil[8]  = 'millones de billones'; 
	   $matmil[10] = 'trillones'; 
	   $matmil[11] = 'de trillones'; 
	   $matmil[12] = 'millones de trillones'; 
	   $matmil[13] = 'de trillones'; 
	   $matmil[14] = 'billones de trillones'; 
	   $matmil[15] = 'de billones de trillones'; 
	   $matmil[16] = 'millones de billones de trillones'; 

	   $num = trim((string)@$num); 
	   if ($num[0] == '-') { 
		  $neg = 'menos '; 
		  $num = substr($num, 1); 
	   }else 
		  $neg = ''; 
	   while ($num[0] == '0') $num = substr($num, 1); 
	   if ($num[0] < '1' or $num[0] > 9) $num = '0' . $num; 
	   $zeros = true; 
	   $punt = false; 
	   $ent = ''; 
	   $fra = ''; 
	   for ($c = 0; $c < strlen($num); $c++) { 
		  $n = $num[$c]; 
		  if (! (strpos(".,'''", $n) === false)) { 
			 if ($punt) break; 
			 else{ 
				$punt = true; 
				continue; 
			 } 

		  }elseif (! (strpos('0123456789', $n) === false)) { 
			 if ($punt) { 
				if ($n != '0') $zeros = false; 
				$fra .= $n; 
			 }else 

				$ent .= $n; 
		  }else 

			 break; 

	   } 
	   $ent = '     ' . $ent; 
	   if ($dec and $fra and ! $zeros) { 
		  $fin = ''; 
		  for ($n = 0; $n < strlen($fra); $n++) { 
			 if (($s = $fra[$n]) == '0') 
				$fin .= $s; 
			 elseif ($s == '1') 
				$fin .= $s; 
			 else 
				$fin .= $s ;
		  } 
				
	   }else 
		  $fin = ''; 
	   if ((int)$ent === 0) return 'Cero ' . $fin; 
	   $tex = ''; 
	   $sub = 0; 
	   $mils = 0; 
	   $neutro = false; 
	   while ( ($num = substr($ent, -3)) != '   ') { 
		  $ent = substr($ent, 0, -3); 
		  if (++$sub < 3 and $fem) { 
			 $matuni[1] = 'uno'; 
			 $subcent = 'os'; 
		  }else{ 
			 $matuni[1] = $neutro ? 'un' : 'uno'; 
			 $subcent = 'os'; 
		  } 
		  $t = ''; 
		  $n2 = substr($num, 1); 
		  if ($n2 == '00') { 
		  }elseif ($n2 < 21) 
			 $t = ' ' . $matuni[(int)$n2]; 
		  elseif ($n2 < 30) { 
			 $n3 = $num[2]; 
			 if ($n3 != 0) $t = 'i' . $matuni[$n3]; 
			 $n2 = $num[1]; 
			 $t = ' ' . $matdec[$n2] . $t; 
		  }else{ 
			 $n3 = $num[2]; 
			 if ($n3 != 0) $t = ' y ' . $matuni[$n3]; 
			 $n2 = $num[1]; 
			 $t = ' ' . $matdec[$n2] . $t; 
		  } 
		  $n = $num[0]; 
		  if ($n == 1) { 
			 $t = ' ciento' . $t; 
		  }elseif ($n == 5) { 
			 $t = ' ' . $matunisub[$n] . 'ient' . $subcent . $t; 
		  }elseif ($n != 0) { 
			 $t = ' ' . $matunisub[$n] . 'cient' . $subcent . $t; 
		  } 
		  if ($sub == 1) { 
		  }elseif (! isset($matsub[$sub])) { 
			 if ($num == 1) { 
				$t = ' mil'; 
			 }elseif ($num > 1) { 
				$t .= ' mil'; 
			 } 
		  }elseif ($num == 1) { 
			 $t .= ' ' . $matsub[$sub] . '?n'; 
		  }elseif ($num > 1) { 
			 $t .= ' ' . $matsub[$sub] . 'ones'; 
		  }   
		  if ($num == '000') $mils ++; 
		  elseif ($mils != 0) { 
			 if (isset($matmil[$sub])) $t .= ' ' . $matmil[$sub]; 
			 $mils = 0; 
		  } 
		  $neutro = true; 
		  $tex = $t . $tex; 
	   } 
	   
	   	if($fin == '') {
	   	$vr = '00';
		}elseif($fin=='1' || $fin=='2' || $fin=='3' || $fin=='4' || $fin=='5' || $fin=='6' || $fin=='7' || $fin=='8' || $fin=='9') {
			$vr = $fin . '0';
			}elseif($fin == '01') {
				$vr = $fin;
				}else
					$vr = $fin;


		if($mon == 'MXN') {
			$moneda = ' PESOS ';
			$monAbrev = ' M.N.';
		}else{
			$SQL = "SELECT * FROM sat_currency WHERE abrev = '$mon' LIMIT 1;";
			$infoMon = mysql_fetch_assoc(mysql_query($SQL));
			$moneda = ' '.$infoMon['nombre'].' ';
			$monAbrev = ' '.$mon;
		}

		$vr = substr($vr, 0, 2);
		$tex = $neg.substr($tex, 1).$moneda.$vr.'/100 '.$monAbrev; 
		return strtoupper($tex); 
	}

?>