<?php 
	include 'header.phtml';

	if(isset($_SESSION['sucursal']) && (!isset($solicitudes) || count($solicitudes)==0)):
?>
	<link href="<?=URL_ROOT?>/assets/plugins/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
			
	<div class="row page-titles">
		<div class="col-md-5 align-self-center">
			<h3 class="text-themecolor"><i class="mdi mdi-chart-areaspline"></i> Reportes</h3>
		</div>
	</div>
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-body">
						<h4 class="card-title">Reportes de ventas por producto</h4>
						<h6 class="card-subtitle">Seleccione un periodo de ventas y una sucursal para generar el reporte</h6>
								
						<div class="row">
							<div class="col-sm-4">
								<div class="input-group sucursal">
									<div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-home"></i></span></div>
									<select class="form-control" id="busSuc">
										<option value="0">Todas las Sucursales</option>
										<?php foreach ($sucursales as $suc) {
											echo '<option value="'.$suc->id.'">'.$suc->nombre.'</option>';
										}
										?>
									</select>
								</div>
							</div>
							<!-- <div class="col-sm-3">
								<div class="input-group">
									<div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-cubes"></i></span></div>
									<select class="form-control" id="busCat">
										<option value="0">Categoría</option>
										<?php foreach ($categorias as $cat) {
											echo '<option value="'.$cat->id.'">'.$cat->nombre.'</option>';
										}
										?>
									</select>
								</div>
							</div> -->
							<div class="col-sm-4">
								<div class="input-group">
									<div class="input-group-prepend"><span class="input-group-text"><i class="mdi mdi-clipboard-account"></i></span></div>
									<select class="form-control" id="filtro_periodo">
										<option value="0">Mensual</option>
										<option value="1">Semanal</option>
										<option value="2">Diario</option>
									</select>
								</div>
							</div>
							<div class="col-sm-4">
								<div class="form-group mb-0">
									<div class="input-group">
										<div class="input-group-prepend">
											<span class="input-group-text"><i class="fa fa-calendar"></i></span>
										</div>
										<select class="form-control" id="filtro_semana" >
          								</select>
										<select class="form-control" id="filtro_mensual">
										</select>
										<input class="form-control input-daterange-datepicker" type="text" id="fechas" value="<?= date("d/m/Y",strtotime(date("01-m-Y"))) . ' - ' . date('d/m/Y') ?>" />
									</div>
								</div>
							</div>
							</div>
						</div>
						<hr>
						<div class="table-responsive">
							<table id="tbl-items" class="table table-hover table-striped m-t-0 m-b-0">
								<thead>
									<tr>
										<th>Producto</th>
										<th class="text-center">Cantidad</th>
										<th class="text-right">Monto</th>
									</tr>
								</thead>
								<tbody>
									<tr><td colspan="3"><small>Seleccione un periodo</small></td></tr>
								</tbody>
								<tfoot>
									<tr>
										<th colspan="1"><small></small></th>
										<th colspan="1" id="totalTablaC" class="text-center">0</th>
										<th id="totalTabla" class="text-right"></th>
									</tr>
								</tfoot>
							</table>
						</div>
						<div class="row hide">
							<div class="col-sm-6">
								<div class="dataTables_length" id="editable-datatable_length">
									<label>
										<select name="editable-datatable_length" aria-controls="editable-datatable" class="form-control input-sm" id="cont">
											<option value="100">Ver 100</option>
											<option value="10">Ver 10</option>
											<option value="25">Ver 25</option>
											<option value="50">Ver 50</option>
										</select>
									</label>
									<span id="reg" class="heading-text"></span>
								</div>
							</div>
							<div class="col-sm-6">
								<div class="card-body">
									<nav aria-label="Page navigation example">
										<ul id="pag" class="pagination pull-right"></ul>
									</nav>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php include 'footer.phtml';?>
	<script src="<?=URL_ROOT?>/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/typeahead.js-master/dist/typeahead.bundle.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/plugins/select2/dist/js/select2.full.min.js" type="text/javascript"></script>

	<script type="text/javascript">
		$(function() {
			$apiUrl = '<?= URL_API ?>venta/';
            $('#mnu-rpt').addClass('active');
			$('.input-daterange-datepicker').daterangepicker({
				buttonClasses: ['btn', 'btn-sm'],
				applyClass: 'btn-primary',
				cancelClass: 'btn-inverse',
				maxDate: '<?= date('d/m/Y') ?>',
				locale: $dateRangeLocale,
				ranges: $dateRanges,
				alwaysShowCalendars: true,
				singleDatePicker: true,
				autoApply: true
			}, function(start, end, label) {
				getItems(0,100,$('#filtro_mensual').val(), $('#filtro_semana').val() );
			});

			$('#filtro_periodo').val('0');
			$('#filtro_periodo').change(function(){
				if ($('#filtro_periodo').val() == 0) {
					$('#filtro_mensual').empty();
					$('#filtro_mensual').append('<option value="1">  Enero  </option>');
					$('#filtro_mensual').append('<option value="2">  Febrero  </option>');
					$('#filtro_mensual').append('<option value="3">  Marzo  </option>');
					$('#filtro_mensual').append('<option value="4">  Abril  </option>');
					$('#filtro_mensual').append('<option value="5">  Mayo  </option>');
					$('#filtro_mensual').append('<option value="6">  Junio  </option>');
					$('#filtro_mensual').append('<option value="7">  Julio  </option>');
					$('#filtro_mensual').append('<option value="8">  Agosto  </option>');
					$('#filtro_mensual').append('<option value="9">  Septiembre  </option>');
					$('#filtro_mensual').append('<option value="10"> Octubre  </option>');
					$('#filtro_mensual').append('<option value="11"> Noviembre  </option>');
					$('#filtro_mensual').append('<option value="12"> Diciembre  </option>');
					$('#filtro_mensual').show();
					$('#filtro_semana').hide();
					$('#fechas').hide();
				}else if ($('#filtro_periodo').val() == 1) {
					moment.lang('es', {
					  months: 'Enero_Febrero_Marzo_Abril_Mayo_Junio_Julio_Agosto_Septiembre_Octubre_Noviembre_Diciembre'.split('_'),
					  monthsShort: 'Enero._Feb._Mar_Abr._May_Jun_Jul._Ago_Sept._Oct._Nov._Dec.'.split('_'),
					  weekdays: 'Domingo_Lunes_Martes_Miercoles_Jueves_Viernes_Sabado'.split('_'),
					  weekdaysShort: 'Dom._Lun._Mar._Mier._Jue._Vier._Sab.'.split('_'),
					  weekdaysMin: 'Do_Lu_Ma_Mi_Ju_Vi_Sa'.split('_')
					}
					);
					// MES ANTERIOR
					$('#filtro_semana').empty();
					$('#fechas').hide();
					$('#filtro_mensual').hide();
					$('#filtro_semana').show();
					$('#filtro_semana').append('<option value="1">' + moment().subtract(1, 'months').startOf('month').format('DD') + ' - ' + moment().subtract(1, 'months').add(0, 'weeks').endOf('isoWeek').format('DD MMMM')+  '</option>');
					$('#filtro_semana').append('<option value="2">' + moment().subtract(1, 'months').add(1, 'weeks').startOf('isoWeek').format('DD') + ' - ' + moment().subtract(1, 'months').add(1, 'weeks').endOf('isoWeek').format('DD MMMM')+  '</option>');
					$('#filtro_semana').append('<option value="3">' + moment().subtract(1, 'months').add(2, 'weeks').startOf('isoWeek').format('DD') + ' - ' + moment().subtract(1, 'months').add(1, 'weeks').endOf('isoWeek').format('DD MMMM')+  '</option>');
					$('#filtro_semana').append('<option value="4">' + moment().subtract(1, 'months').add(3, 'weeks').startOf('isoWeek').format('DD') + ' - ' + moment().subtract(1, 'months').endOf('month').format('DD MMMM')+  '</option>');
					// MES ACTUAL
					$('#filtro_semana').append('<option value="5">' + moment().startOf('month').format('DD')                   + ' - ' + moment().add(0, 'weeks').endOf('isoWeek').format('DD MMMM')+  '</option>');
					$('#filtro_semana').append('<option value="6">' + moment().add(1, 'weeks').startOf('isoWeek').format('DD') + ' - ' + moment().add(1, 'weeks').endOf('isoWeek').format('DD MMMM')+  '</option>');
					$('#filtro_semana').append('<option value="7">' + moment().add(2, 'weeks').startOf('isoWeek').format('DD') + ' - ' + moment().add(1, 'weeks').endOf('isoWeek').format('DD MMMM')+  '</option>');
					$('#filtro_semana').append('<option value="8">' + moment().add(3, 'weeks').startOf('isoWeek').format('DD') + ' - ' + moment().endOf('month').format('DD MMMM')+  '</option>');
				}else if ($('#filtro_periodo').val() == 2) {
					$('#fechas').append('<input class="form-control input-daterange-datepicker" type="text" id="fechas" value="<?= date("d/m/Y",strtotime(date("01-m-Y"))) . ' - ' . date('d/m/Y') ?>" />');
					$('#fechas').show();
					$('#filtro_mensual').hide();
					$('#filtro_semana').hide();
				}
			});
			$('#filtro_periodo').trigger('change');
			getItems(0, 100, 1, 0); 
			function getItems(pag, lim, mensual , filtro1 ) {
				vend = $('#filtro_periodo').val();
				if(vend == 0 || vend == 1 || vend == 2){
					$('#tbl-items tbody').empty();
					blockPage();
					suc = $('#busSuc').val();
					cat = $('#busCat').val();
					// (mensual == '') ? mensual = 0 : mensual = $('#filtro_mensual').val();
					mensual = $('#filtro_mensual').val();
					// filtro1 = $('#filtro_semana').val();
					(filtro1 == '' || filtro1 == null) ? filtro1 = 0 : filtro1 = $('#filtro_semana').val();
					var fechas = $('#fechas').data('daterangepicker');
					
					if(vend == 0){
						switch (mensual) {
							case '1':
									ini = moment().startOf('month').set({'month': 0}).format('YYYY-MM-DD');
									fin = moment().endOf('month').set({'month': 0}).format('YYYY-MM-DD');
								break;

								case '2':
									ini = moment().startOf('month').set({'month': 1}).format('YYYY-MM-DD');
									fin = moment().endOf('month').set({'month': 1}).format('YYYY-MM-DD');
								break;

								case '3':
									ini = moment().startOf('month').set({'month': 2}).format('YYYY-MM-DD');
									fin = moment().endOf('month').set({'month': 2}).format('YYYY-MM-DD');
								break;
									
								case '4':
									ini = moment().startOf('month').set({'month': 3}).format('YYYY-MM-DD');
									fin = moment().endOf('month').set({'month': 3}).format('YYYY-MM-DD');
								break;
									
								case '5':
									ini = moment().startOf('month').set({'month': 4}).format('YYYY-MM-DD');
									fin = moment().endOf('month').set({'month': 4}).format('YYYY-MM-DD');
								break;

								case '6':
									ini = moment().startOf('month').set({'month': 5}).format('YYYY-MM-DD');
									fin = moment().endOf('month').set({'month': 5}).format('YYYY-MM-DD');
								break;

								case '7':
									ini = moment().startOf('month').set({'month': 6}).format('YYYY-MM-DD');
									fin = moment().endOf('month').set({'month': 6}).format('YYYY-MM-DD');
								break;

								case '8':
									ini = moment().startOf('month').set({'month': 7}).format('YYYY-MM-DD');
									fin = moment().endOf('month').set({'month': 7}).format('YYYY-MM-DD');
								break;

								case '9':
									ini = moment().startOf('month').set({'month': 8}).format('YYYY-MM-DD');
									fin = moment().endOf('month').set({'month': 8}).format('YYYY-MM-DD');
								break;

								case '10':
									ini = moment().startOf('month').set({'month': 9}).format('YYYY-MM-DD');
									fin = moment().endOf('month').set({'month': 9}).format('YYYY-MM-DD');
								break;
								
								case '11':
									ini = moment().startOf('month').set({'month': 10}).format('YYYY-MM-DD');
									fin = moment().endOf('month').set({'month': 10}).format('YYYY-MM-DD');
								break;

								case '12':
									ini = moment().startOf('month').set({'month': 11}).format('YYYY-MM-DD');
									fin = moment().endOf('month').set({'month': 11}).format('YYYY-MM-DD');
								break;
								
						}
					} else if (vend == 1) {
						switch (filtro1) {
								case '1':
									ini = moment().subtract(1, 'months').startOf('month').format('YYYY-MM-DD');
									fin = moment().subtract(1, 'months').add(0, 'weeks').endOf('isoWeek').format('YYYY-MM-DD');
								break;

								case '2':
									ini = moment().subtract(1, 'months').add(1, 'weeks').startOf('isoWeek').format('YYYY-MM-DD');
									fin = moment().subtract(1, 'months').add(1, 'weeks').endOf('isoWeek').format('YYYY-MM-DD');
								break;

								case '3':
									ini = moment().subtract(1, 'months').add(2, 'weeks').startOf('isoWeek').format('YYYY-MM-DD');
									fin = moment().subtract(1, 'months').add(2, 'weeks').endOf('isoWeek').format('YYYY-MM-DD');
								break;
									
								case '4':
									ini = moment().subtract(1, 'months').add(3, 'weeks').startOf('isoWeek').format('YYYY-MM-DD');
									fin = moment().subtract(1, 'months').endOf('month').format('YYYY-MM-DD');
								break;

								case '5':
									ini = moment().startOf('month').format('YYYY-MM-DD');
									fin = moment().add(0, 'weeks').endOf('isoWeek').format('YYYY-MM-DD');
								break;

								case '6':
									ini = moment().add(1, 'weeks').startOf('isoWeek').format('YYYY-MM-DD');
									fin = moment().add(1, 'weeks').endOf('isoWeek').format('YYYY-MM-DD');
								break;

								case '7':
									ini = moment().add(2, 'weeks').startOf('isoWeek').format('YYYY-MM-DD');
									fin = moment().add(2, 'weeks').endOf('isoWeek').format('YYYY-MM-DD');
								break;
									
								case '8':
									ini = moment().add(3, 'weeks').startOf('isoWeek').format('YYYY-MM-DD');
									fin = moment().endOf('month').format('YYYY-MM-DD');
								break;
						}
					}else if(vend == 2){
						ini = fechas.startDate.format('YYYY-MM-DD');
						fin = fechas.endDate.format('YYYY-MM-DD');
					}
					$.get($apiUrl+'getVentasByProducto/'+ini+'/'+fin+'/'+suc+'/'+cat, function(resp) {
						if(resp.result.length > 0) {
							if ( $.fn.dataTable.isDataTable( '#tbl-items' ) ) {
								$('#tbl-items').DataTable().destroy();
							}
							$('#tbl-items tbody').empty();
							container = $('<div class="form-inline"></div>');
							prods = 0;
							
							$.each(resp.result, function(index, item) {

								addRow(item);
								// $.each(item, function (index, det) { 
									prods+=parseInt(item.total_cantidad); 
								// });
							});

							function getTrElement(tblName, tr) {
								container1 = $('<div></div>');
								trInfo = $('#'+tblName).DataTable().row(tr).data();
								$.each(trInfo, function(index, trInfoRow) {
									container1.append(trInfoRow);
								});
							
								return container1;
							}
						
							function calcTot(tbl){
								tot = 0;
								$.each($('#'+tbl).DataTable().rows({filter: 'applied'})[0], function(index, tr) {
									precio = getTrElement(tbl, tr).text().split('$')[1];
									imp = parseFloat(precio);	
									tot += imp;
								});
								return tot;
							}

							function calcTot1(tbl){
								tot1 = 0;
								$.each($('#'+tbl).DataTable().rows({filter: 'applied'})[0], function(index, tr) {
									cantidad = getTrElement(tbl, tr).html().split('</small>')[1].split('$')[0];
									imp = parseFloat(cantidad);	
									tot1 += imp;
								});
								return tot1;
							}
							$('#tbl-items tfoot th:eq(0) small').html(prods+' productos en '+resp.result.length+' ventas registradas en el periodo');
							$('#tbl-items tfoot th:eq(2)').html('$ '+resp.total);

							order = [1, 'desc'];

							searchContainer = $('<div class="input-group"></div>').appendTo(container);
							searchContainer.append('<div class="input-group-prepend"><div class="input-group-text"><span class="fa fa-filter"></span></div></div>');
							search = $('<input type="text" id="bus" placeholder="Buscar" class="form-control">').appendTo(searchContainer);
							searchContainer.append('<input type="hidden" id="producto-id" value="0">');
							search.keyup(function(e) { $("#tbl-items"+"_filter label input").val($.trim($(this).val())).trigger('keyup'); });
							search.on("search", function(evt) { $("#tbl-items"+"_filter label input").val(undefined).trigger('keyup'); });
							
							buttonsContainer = $('<div class="buttons"></div>').appendTo(container);
							buttonPDF = $('<button type="button" class="btn ml-2 btn-sm btn-inline-block" title="Exportar a PDF"><span class="mdi mdi-file-pdf-box fa-2x" style="color: red;"></span></button>').appendTo(buttonsContainer);
							buttonExcel = $('<button type="button" class="btn btn-sm btn-inline-block" title="Exportar a Excel"><span class="mdi mdi-file-excel-box fa-2x" style="color: green;"></span></button>').appendTo(buttonsContainer);
							$('[data-toggle="tooltip"]').tooltip();

							$('#tbl-items').DataTable({
								"paging":   false,
								// "searching": false,
								'dom': 'Bl<"#toolbar-tbl-items">frtip',
								"info":     false,
								'order': order,
								'fnDrawCallback': function() {
								$('#totalTabla').html(new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(calcTot('tbl-items')));
								$('#totalTablaC').html('Totales:  ' + calcTot1('tbl-items'));
								},
								'buttons': [
									'excelHtml5',
									// 'pdfHtml5'
									{
										extend: 'pdfHtml5',
										title: 'Reporte de ventas por producto | Telecom',
										customize: function(doc) {
											// doc.pageOrientation = 'landscape',
											doc.pageMargins = [40, 10, 10, 10],
											doc.defaultStyle.fontSize = 10
										}
									}
								]
							});

							$('#toolbar-tbl-items').html(container).addClass('pull-right');
							$("#tbl-items"+"_filter label").hide();
							$('#tbl-items').parents('.table-responsive').css('overflow', 'visible');
							$.each($($('#tbl-items').DataTable().buttons()), function(index, item) { $(item.node).addClass('hide') });
							buttonPDF.click(function(e) { e.preventDefault(); $('#tbl-items').DataTable().buttons()[1].node.click() });
							buttonExcel.click(function(e) { e.preventDefault(); $('#tbl-items').DataTable().buttons()[0].node.click() });

						}else{
							$('#tbl-items tbody').append('<tr><td colspan="3"><small>No existen ventas para este producto en el periodo</small></td></tr>');
							$('#tbl-items tfoot th:eq(0) small').html('');
							$('#tbl-items tfoot th:eq(1)').html('');
							$('#tbl-items tfoot th:eq(2)').html('$ '+resp.total);
						}
						$.unblockUI();
					});
				}
			}

			function addRow(item) {
				tr = $('<tr data-ent="'+item.id+'"></tr>');
				if($('#tbl-items [data-id="'+item.id+'"]').length > 0) {
					tr = $('#tbl-items [data-id="'+item.id+'"]').parents('tr');
					tr.empty();
				}

				// rspan = item.detalles.length;
				// btnPrint = '';//'<a href="<?= URL_ROOT ?>/venta/print/'+item.id+'?dl=1" target="_blank" data-popup="tooltip" title="Imprimir" class="btnPrint"><i class="mdi mdi-printer"></i></a> ';

				// $.each(item, function(index, det) {
					item.sku = item.sku == null ? '' : item.sku;
					tr.append('<td><small>'+item.nombre+' '+item.modelo+'</small></td>');
					tr.append('<td class="text-center">'+item.total_cantidad+'</td>');
					tr.append('<td class="text-right">$ '+item.total+'</td>');

					$('#tbl-items tbody').append(tr);
					tr = $('<tr data-ent="'+item.id+'"></tr>');
				// });
			}
		
			$("#filtro_periodo, #busCat, #busSuc, #filtro_mensual, #filtro_semana").change(function () { getItems(0, $("#cont").val(), $('#filtro_mensual').val(), $('#filtro_semana').val()); });
		});
		
	</script>
<?php else: include 'footer.phtml'; endif; ?>