<?php 
	include 'header.phtml';

	define('MOD_SUELDOS', 	111);
	define('MOD_EDIT_SUELDO', 	112);

	$admin = $_SESSION['sucursal'] == 0 ? true : false;
	
	if(isset($_SESSION['sucursal']) && (!isset($solicitudes) || count($solicitudes)==0)):
?>

	<div class="row page-titles">
		<div class="col-md-5 align-self-center">
			<h3 class="text-themecolor"><i class="mdi mdi-cash-multiple fa-lg"></i> Sueldos</h3>
		</div>
		<div class="col-md-7 align-self-center text-right">
			<small><?= $fechaLarga ?></small>
		</div>
	</div>
	<div class="container-fluid">
		<div class="card saldos">
			<div class="card-header">
				<div class="pull-right form">
					<div class="input-group input-group-sm">
						<input type="text" id="bus" placeholder="Buscar por nombre" class="form-control form-control-sm">
						<div class="input-group-append">
							<span class="input-group-text"><i class="fa fa-search"></i></span>
						</div>
					</div>
				</div>
				
				<h4 class="card-title"><i class="mdi mdi-account-star-variant"></i> Vendedores</h4>
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table id="tbl-items" class="table table-hover table-striped">
						<thead>
							<tr>
								<th>Nombre</th>
								<th class="text-center">Sueldo</th>
								<th class="text-center">Comisiones</th>
								<th class="text-center">Deudas</th>
								<th class="text-center">Abonos</th>
								<th class="text-center">Pago</th>
							</tr>
						</thead>
						<tbody></tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<?php include 'footer.phtml';?>
	<script src="<?=URL_ROOT?>/assets/plugins/inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
	<script src="<?=URL_ROOT?>/assets/js/mask.init.js"></script>

	<script type="text/javascript">
		$(function() {

			$apiUrl = '<?= URL_API ?>usuario/';

			getItems();
			function getItems() {
				blockPage();
				$('#tbl-items tbody').empty();
				$.get($apiUrl+"getSueldos",
					function (data) {
						$.each(data, function(index, item) {
							addRow(item);
						});
						$('#tbl-items input').inputmask({ alias: "numeric", groupSeparator: ',', digits: 2, digitsOptional: false, placeholder: '0.00' });
						$.unblockUI();
					},
					"json"
				);
			}

			function addRow(item) {
				tr = $('<tr data-id="'+item.id+'"></tr>');
				tr.append('<td>'+item.nombre+'</td>');
				<?php if(in_array(MOD_EDIT_SUELDO, $permisos)) : ?>
				sueldo = '<input type="text" min="0" class="form-control form-control-sm text-center edit-pago" data-field="sueldo" value="'+item.pago.sueldo+'">';
				comision = '<input type="text" min="0" class="form-control form-control-sm text-center edit-pago" data-field="comision" value="'+item.pago.comision+'">';
				deudas = '<input type="text" min="0" class="form-control form-control-sm text-center edit-pago" data-field="deudas" value="'+item.pago.deudas+'">';
				abono = '<input type="text" min="0" class="form-control form-control-sm text-center edit-pago" data-field="abono" value="0.00" '+(item.pago.deudas==0.00?'readonly':'')+'>';
				tr.append('<td class="text-center">'+sueldo+'</td>');
				tr.append('<td class="text-center">'+comision+'</td>');
				tr.append('<td class="text-center">'+deudas+'</td>');
				tr.append('<td class="text-center">'+abono+'</td>');
				<?php else : ?>
				tr.append('<td class="text-center">'+item.pago.sueldo+'</td>');
				tr.append('<td class="text-center">'+item.pago.comision+'</td>');
				tr.append('<td class="text-center">'+item.pago.deudas+'</td>');
				tr.append('<td class="text-center">'+item.pago.abono+'</td>');
				<?php endif; ?>
				tr.append('<th class="text-center">'+item.pago.pago+'</th>');

				$('#tbl-items tbody').append(tr);
			}
			
			$('body').on('change','.edit-pago', function(){
				tr = $(this).parents('tr');
				sueldo = parseFloat(tr.find('input:eq(0)').val());
				comision = parseFloat(tr.find('input:eq(1)').val());
				abono = parseFloat(tr.find('input:eq(3)').val());

				pago = sueldo + comision - abono;
				field = $(this).data('field');

				data = {user: tr.data('id'), pago: pago};
				if(field == 'abono'){
					deudas = parseFloat(tr.find('input:eq(2)').val());
					if(abono > deudas){
						swal({
							type: "warning",
							title: "Abonar a deuda",   
							text: "No puedes abonar mas de la deuda actual",   
							timer: 3000
						});
						tr.find('input:eq(3)').val('0.00');
						return false;
					}else{
						deuda = (deudas - abono).toFixed(2);
						tr.find('input:eq(2)').val(deuda);
						data['deudas'] = deuda;
						tr.find('input:eq(3)').prop('readonly', !(deuda > 0.00));
					}
				}else{
					data[field] = $(this).val();
				}
				blockPage();
				$.post($apiUrl+"editPago", data,
					function (data) {
						tr.find('th').text(pago.toFixed(2));
						if(field=='abono'){
							swal({
								type: "success",
								title: "Abonar a deuda",   
								text: "Se abonaron correctamente <strong class='font-weight-bold'>"+abono.toFixed(2)+"</strong> a la deuda",
								html: true, 
								timer: 5000
							});
							tr.find('input:eq(3)').val('0.00');
							tr.find('input:eq(3)').prop('readonly', !(deuda > 0.00));
						}
						$.unblockUI();
					},
					"json"
				);
				if(field == 'deudas') tr.find('input:eq(3)').prop('readonly', !(parseFloat($(this).val()) > 0.00));
			});

			$('#bus').keyup(function(e) { 
				q = $.trim($(this).val()).toUpperCase();
				$.each($('#tbl-items tbody tr'), function (index, elem) { 
					suc = $(elem).find('td:eq(0)').text().toUpperCase();
					if(suc.indexOf(q) > -1){
						$(elem).css('display', '');
					}else{
						$(elem).css('display', 'none');
					}
				});
			 });

			 $("#bus").on("search", function(evt){
				$.each($('#tbl-items tbody tr'), function (index, elem) { 
					$(elem).css('display', '');
				});
			});
		});
		
	</script>
<?php else: include 'footer.phtml'; endif; ?>